name: 'Build Docs'
description: 'Builds the documentation'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env

    - name: Copy OpenAPI Spec
      shell: bash
      working-directory: Networth.Docs
      run: cp ../openapi.json static/openapi.json

    - name: Install dependencies
      shell: bash
      working-directory: Networth.Docs
      run: npm ci

    - name: Typecheck
      shell: bash
      working-directory: Networth.Docs
      run: npm run typecheck

    - name: Build
      shell: bash
      working-directory: Networth.Docs
      run: npm run build
      env:
        API_SPEC_URL: "openapi.json"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: Networth.Docs/build
