name: "Setup Build Environment"
description: "Sets up the build environment for Networth"

runs:
  using: "composite"
  steps:
    - name: Setup Docker
      uses: docker/setup-docker-action@e61617a16c407a86262fb923c35a616ddbe070b3 # v4.6.0
      with:
        version: v28.0.1

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: "24.x"

    - name: Install Azure Functions Core Tools
      shell: bash
      run: npm install -g azure-functions-core-tools@4

    - name: Install Azurite
      shell: bash
      run: npm install -g azurite

    - name: Setup .NET
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
      with:
        global-json-file: global.json

    - name: Print .NET info
      shell: bash
      run: dotnet --info

    - name: Install Aspire workload
      shell: bash
      run: dotnet workload install aspire

    - name: Install & trust dev-certs
      shell: bash
      run: dotnet dev-certs https --trust
