name: 'Build Backend'
description: 'Builds and tests the backend'
inputs:
  gocardless-secret-id:
    description: 'GoCardless Secret ID'
    required: true
  gocardless-secret-key:
    description: 'GoCardless Secret Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=true" >> $GITHUB_ENV
        echo "DOTNET_MULTILEVEL_LOOKUP=false" >> $GITHUB_ENV
        echo "ASPIRE_ALLOW_UNSECURED_TRANSPORT=true" >> $GITHUB_ENV
        echo "SuppressNETCoreSdkPreviewMessage=true" >> $GITHUB_ENV
        echo "DCP_DIAGNOSTICS_LOG_LEVEL=debug" >> $GITHUB_ENV
        echo "TESTCONTAINERS_RYUK_DISABLED=false" >> $GITHUB_ENV
        echo "TESTCONTAINERS_HOST_OVERRIDE=localhost" >> $GITHUB_ENV
        echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV
        echo "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=false" >> $GITHUB_ENV

    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env

    - name: Restore dependencies
      shell: bash
      run: dotnet restore Networth.sln

    - name: Build solution
      shell: bash
      run: dotnet build Networth.sln --no-restore --configuration Release

    - name: Install Playwright browsers
      shell: bash
      run: pwsh Tests/Networth.SystemTests/bin/Release/net9.0/playwright.ps1 install --with-deps chromium

    - name: Test
      id: test
      shell: bash
      env:
        Parameters__gocardless-secret-id: ${{ inputs.gocardless-secret-id }}
        Parameters__gocardless-secret-key: ${{ inputs.gocardless-secret-key }}
        Parameters__postgres-password: "test-password-123!"
      run: >
        dotnet test Networth.sln
        --no-build
        --configuration Release
        --logger "console;verbosity=normal"
        --logger trx
        --results-directory ./TestResults
        --blame
        --collect:"XPlat Code Coverage"
        -- RunConfiguration.CollectSourceInformation=true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: TestResults/**/*.trx
        reporter: dotnet-trx

    - name: Copy DCP logs
      if: (success() || steps.test.conclusion == 'failure')
      shell: bash
      run: |
        mkdir -p ./TestResults/DCPLogs
        if [ -d "/tmp/dcp/logs" ]; then
          cp -r /tmp/dcp/logs/* ./TestResults/DCPLogs 2>/dev/null || true
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: test-results
        path: ./TestResults/
        if-no-files-found: error
