name: "Build Frontend"
description: "Builds and tests the frontend"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: "npm"
        cache-dependency-path: Networth.Frontend/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: Networth.Frontend
      run: npm ci

    - name: Lint
      shell: bash
      working-directory: Networth.Frontend
      run: npm run lint

    - name: Test
      shell: bash
      working-directory: Networth.Frontend
      run: npm test -- --run

    - name: Build
      shell: bash
      working-directory: Networth.Frontend
      run: npm run build
