api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--postgresdb
        value: Host=postgres;Port=5432;Username=postgres;Password={{ securedParameter "postgres_password" }};Database=postgresdb
  template:
    containers:
      - image: {{ .Image }}
        name: functions
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Aspire__Azure__Data__Tables__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_TABLEENDPOINT }}'
          - name: Aspire__Azure__Storage__Blobs__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_BLOBENDPOINT }}'
          - name: Aspire__Azure__Storage__Queues__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_QUEUEENDPOINT }}'
          - name: AzureFunctionsJobHost__telemetryMode
            value: OpenTelemetry
          - name: AzureWebJobsStorage__blobServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_BLOBENDPOINT }}'
          - name: AzureWebJobsStorage__queueServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_QUEUEENDPOINT }}'
          - name: AzureWebJobsStorage__tableServiceUri
            value: '{{ .Env.FUNCSTORAGEF2721_TABLEENDPOINT }}'
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet-isolated
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__postgresdb
            secretRef: connectionstrings--postgresdb
    scale:
      minReplicas: 1
tags:
  azd-service-name: functions
  aspire-resource-name: functions
