name: Frontend

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: |
            frontend:
              - "Networth.Frontend/**"
              - ".github/actions/build-frontend/**"

  build-and-test-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    name: Build & Test - Frontend
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.1.0
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: Networth.Frontend/package-lock.json

      - name: Install dependencies
        shell: bash
        working-directory: Networth.Frontend
        run: npm ci

      - name: Lint
        shell: bash
        working-directory: Networth.Frontend
        run: npm run lint

      - name: Test
        shell: bash
        working-directory: Networth.Frontend
        run: npm test -- --run

      - name: Build
        shell: bash
        working-directory: Networth.Frontend
        run: npm run build
